name: my_project

environment:
  sdk: '>=3.6.0 <4.0.0'

workspace:
  - packages/serinus
  - packages/serinus_cli
  - packages/serinus_config
  - packages/serinus_frontier
  - packages/serinus_openapi
  - packages/serve_static
  - packages/serinus_test
  - packages/serinus_microservices
  - packages/serinus_lint
  - examples/grpc_example