name: serinus_serve_static
description: "A Serinus Plugin to serve static files in a Serinus Application"
version: 1.0.3
repository: https://github.com/francescovallone/serinus
homepage: https://docs.serinus.app
documentation: https://docs.serinus.app/plugins/serve_static
tag: 
  - server
  - static
  - backend
  - web
  - http


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serinus: ^0.6.0
  
