name: serinus_config
description: A module for Serinus applications that exposes the dotenv package allowing you to load environment variables from a .env file.
version: 2.0.0
repository: https://github.com/francescovallone/serinus
homepage: https://serinus.app/
documentation: https://serinus.app/techniques/configuration.html
topics:
  - server
  - httpserver
  - backend
  - web
  - dotenv

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  dotenv: ^4.2.0
  serinus: ^2.0.0
  
dev_dependencies:
  lints: "^6.0.0"
  test: ^1.26.3
