name: serinus_serve_static_example
description: "A new Serinus application"
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serinus: ^0.5.0
  serinus_serve_static: ^1.0.2
  
