name: serinus_openapi
description: A Serinus plugin to generate OpenAPI documentation from your Serinus app.
version: 1.0.13
repository: https://github.com/francescovallone/serinus
homepage: https://serinus.app
documentation: https://serinus.app/openapi
tag: 
  - server
  - swagger
  - backend
  - web
  - openapi

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  serinus: ^2.0.0
  openapi_types: ^2.0.0
  analyzer: ^8.4.0

dev_dependencies:
  lints: "^6.0.0"
  test: ^1.26.3
  serinus_lint: ^0.1.2
