name: serinus
description: Serinus is a framework written in Dart 
  for building efficient and scalable server-side applications.
documentation: https://serinus.app
homepage: https://serinus.app
repository: https://github.com/francescovallone/serinus
version: 2.1.3
funding:
  - https://github.com/sponsors/francescovallone
topics:
  - server
  - httpserver
  - backend
  - web
  - http

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  async: ^2.13.0
  http_parser: ^4.1.2
  intl: ^0.20.2
  logging: ^1.3.0
  meta: ^1.18.0
  mime: ^2.0.0
  stream_channel: ^2.1.4
  uuid: ^4.5.2
  web_socket_channel: ^3.0.3
  collection: ^1.19.1
  shelf: ^1.4.2
  acanthis: ^1.5.0
  secure_session: ^1.0.5
  crypto: ^3.0.7

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.28.0
  lints: ^6.0.0
  http: ^1.5.0
  test_process: ^2.1.1
  benchmark_harness: 2.3.1
