name: serinus
description: Serinus is a framework written in Dart 
  for building efficient and scalable server-side applications.
documentation: https://serinus.app
homepage: https://serinus.app
repository: https://github.com/francescovallone/serinus
version: 2.0.0-rc.3
funding:
  - https://github.com/sponsors/francescovallone
topics:
  - server
  - httpserver
  - backend
  - web
  - http

environment:
  sdk: '>=3.7.0 <4.0.0'

resolution: workspace

dependencies:
  async: ^2.12.0
  http_parser: ^4.1.2
  intl: ">=0.19.0 <0.21.0"
  logging: ^1.3.0
  meta: ^1.16.0
  mime: ^2.0.0
  spanner: ^1.0.6
  stream_channel: ^2.1.2
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1
  collection: ^1.19.1
  shelf: ^1.4.2
  acanthis: ^1.0.0
  secure_session: ^1.0.5
  web_socket: ^1.0.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.16.0
  lints: ^6.0.0
  http: ^1.2.2
  test_process: ^2.1.1
