name: serinus
description: Serinus is a framework written in Dart 
  for building efficient and scalable server-side applications.
documentation: https://develop.serinus.app
homepage: https://develop.serinus.app
repository: https://github.com/francescovallone/serinus
version: 1.0.0-rc.3
funding:
  - https://www.patreon.com/francescovallone
  - https://github.com/sponsors/francescovallone
topics:
  - server
  - httpserver
  - backend
  - web
  - http

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.12.0
  http_parser: ^4.1.1
  intl: ^0.19.0
  logging: ^1.3.0
  meta: ^1.16.0
  mime: ^2.0.0
  spanner: ^1.0.3
  stream_channel: ^2.1.2
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1
  collection: ^1.19.1
  shelf: ^1.4.2
  acanthis: ^0.1.3
  secure_session: ^1.0.5

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.16.0
  lints: ^3.0.0
  http: ^1.2.2
