name: serinus_cli
description: The official CLI of the Serinus Framework. It allows you to create, build, and manage Serinus projects.
version: 2.1.0
repository: 'https://github.com/francescovallone/serinus'
homepage: https://serinus.app

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  analyzer: ^9.0.0
  args: ^2.7.0
  cli_completion: ^0.5.1
  code_builder: ^4.11.0
  dart_style: ^3.1.1
  http: ^1.6.0
  mason: ^0.1.2
  mason_logger: ^0.3.3
  meta: ^1.17.0
  path: ^1.9.1
  pub_updater: ^0.5.0
  watcher: ^1.2.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.9.0
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0

executables:
  serinus:
