name: serinus_cli
description: The official CLI of the Serinus Framework. It allows you to create, build, and manage Serinus projects.
version: 1.0.10
repository: 'https://github.com/francescovallone/serinus'
homepage: https://serinus.app

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  analyzer: ^7.1.0
  args: ^2.7.0
  cli_completion: ^0.5.1
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  mason: ^0.1.1
  mason_logger: ^0.3.3
  meta: ^1.16.0
  path: ^1.9.1
  pub_updater: ^0.5.0
  watcher: ^1.1.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^7.0.0

executables:
  serinus:
