name: auth_jwt
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  frontier_jwt: ^1.0.1
  serinus: ^2.0.4
  serinus_config: ^2.0.0
  serinus_frontier: ^1.0.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
