name: serinus_swagger
description: A Serinus plugin to generate OpenAPI documentation from your Serinus app.
version: 1.0.3
repository: https://github.com/francescovallone/serinus
homepage: https://docs.serinus.app
documentation: https://docs.serinus.app/plugins/swagger
tag: 
  - server
  - swagger
  - backend
  - web
  - openapi

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serinus: ^1.0.0
  yaml_writer: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
