name: serinus_microservices
description: Microservice transporters and clients for Serinus framework.
version: 0.1.2
repository: https://github.com/francescovallone/serinus
homepage: https://serinus.app
documentation: https://serinus.app/microservices/
topics:
  - server
  - microservices
  - grpc
  - tcp
  - transporters

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  serinus: ^2.1.0
  grpc: ^5.1.0
  protobuf: ^6.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  serinus_lint: ^0.1.0
  
