name: ping_pong
description: A Serinus application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  serinus: 
    path: ../../packages/serinus

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
