name: grpc_example
description: ''
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  serinus: ^2.0.0
  dio: ^5.7.0
  protobuf: ^5.0.0
  grpc: ^4.3.0
  serinus_microservices: ^0.1.0
dev_dependencies:
  build_runner: ^2.4.12
  