name: benchmarks
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # dart_frog: ^1.1.0
  http: ^1.2.1
  serinus: 
    path: ../packages/serinus
  shelf: ^1.4.2
  benchmark_harness: ^2.2.2 
  # vania: ^0.4.1
  # pharaoh: ^0.0.7
  # angel3_framework: ^8.3.2
  shelf_router: ^1.1.4
  

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
