name: serinus_test
description: A test package for Serinus framework. It allows to test their Serinus applications.
version: 0.1.0
repository: https://github.com/francescovallone/serinus

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  serinus: ^2.0.0
  mime: ^2.0.0
  test: ^1.25.6

dev_dependencies:
  lints: ^6.0.0
