name: echo
description: ''
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serinus: ^0.6.2
  dart_mappable: ^4.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
dev_dependencies:
  freezed: ^2.5.7
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.2.3
  json_serializable: ^6.8.0
  
serinus:
  models:
    extensions: 
      - "t"
    deserialize_keywords:
      - keyword: "fromRequest"
        static_method: true
    serialize_keywords:
      - keyword: "toBody"
  client:
    verbose: false
    language: 'Dart'
    httpClient: 'dio'
        