name: Serinus CLI Tests

on:
  pull_request:
    paths:
      - ".github/workflows/serinus_cli.yaml"
      - "packages/serinus_cli/lib/**"
      - "packages/serinus_cli/test/**"
      - "packages/serinus_cli/pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/serinus_cli.yaml"
      - "packages/serinus_cli/lib/**"
      - "packages/serinus_cli/test/**"
      - "packages/serinus_cli/pubspec.yaml"
jobs:
  build:    
    defaults:
      run:
        working-directory: ./packages/serinus_cli
    runs-on: "ubuntu-latest"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: ğŸ“¦ Install Dependencies
        run: dart pub get --no-example

      # - name: ğŸ•µï¸ Analyze
      #   run: dart analyze --fatal-infos --fatal-warnings .

      - name: ğŸ§ª Run Tests
        run: |
          dart pub global activate coverage
          export SERINUS_TEST=true
          dart test --coverage=coverage
      
      # - name: ğŸ“Š Check Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v2
      #   with:
      #     path: ./packages/serinus_cli/coverage/lcov.info
      #     min_coverage: 0
      
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
