name: Serinus Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:    
    defaults:
      run:
        working-directory: ./packages/serinus
    runs-on: "ubuntu-latest"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: ğŸ“¦ Install Dependencies
        run: dart pub -C packages/serinus get

      - name: ğŸ•µï¸ Analyze
        run: dart pub -C packages/serinus analyze --fatal-infos --fatal-warnings .

      - name: ğŸ§ª Run Tests
        run: |
          dart pub global activate coverage
          export SERINUS_TEST=true
          dart pub -C packages/serinus test --coverage=coverage
      
      # - name: ğŸ“Š Check Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v2
      #   with:
      #     path: ./packages/serinus/coverage/lcov.info
      #     min_coverage: 80
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
